INSERT INTO tb_team(name, stadium, color) VALUES ('Vasco da Gama', 'Sao Januario', 'Preto e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Flamengo', 'Maracanã', 'Vermelho e Preto');
INSERT INTO tb_team(name, stadium, color) VALUES ('Corinthians', 'Neo Química Arena', 'Preto e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Palmeiras', 'Allianz Parque', 'Verde e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('São Paulo', 'Morumbi', 'Vermelho, Branco e Preto');
INSERT INTO tb_team(name, stadium, color) VALUES ('Santos', 'Vila Belmiro', 'Branco e Preto');
INSERT INTO tb_team(name, stadium, color) VALUES ('Fluminense', 'Maracanã', 'Verde, Branco e Grená');
INSERT INTO tb_team(name, stadium, color) VALUES ('Botafogo', 'Nilton Santos', 'Preto e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Cruzeiro', 'Mineirão', 'Azul e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Atlético Mineiro', 'Mineirão', 'Preto e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Grêmio', 'Arena do Grêmio', 'Azul, Preto e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Internacional', 'Beira-Rio', 'Vermelho e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Bahia', 'Arena Fonte Nova', 'Azul, Vermelho e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Sport Recife', 'Ilha do Retiro', 'Vermelho e Preto');
INSERT INTO tb_team(name, stadium, color) VALUES ('Vitória', 'Barradão', 'Vermelho e Preto');
INSERT INTO tb_team(name, stadium, color) VALUES ('Athletico Paranaense', 'Arena da Baixada', 'Vermelho e Preto');
INSERT INTO tb_team(name, stadium, color) VALUES ('Coritiba', 'Couto Pereira', 'Verde e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Fortaleza', 'Castelão', 'Vermelho, Azul e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Ceará', 'Castelão', 'Preto e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Real Madrid', 'Santiago Bernabéu', 'Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Barcelona', 'Camp Nou', 'Azul e Grená');
INSERT INTO tb_team(name, stadium, color) VALUES ('Manchester United', 'Old Trafford', 'Vermelho e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Liverpool', 'Anfield', 'Vermelho');
INSERT INTO tb_team(name, stadium, color) VALUES ('Chelsea', 'Stamford Bridge', 'Azul');
INSERT INTO tb_team(name, stadium, color) VALUES ('Arsenal', 'Emirates Stadium', 'Vermelho e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Manchester City', 'Etihad Stadium', 'Azul Claro');
INSERT INTO tb_team(name, stadium, color) VALUES ('Tottenham Hotspur', 'Tottenham Hotspur Stadium', 'Branco e Azul');
INSERT INTO tb_team(name, stadium, color) VALUES ('Bayern Munich', 'Allianz Arena', 'Vermelho e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Borussia Dortmund', 'Signal Iduna Park', 'Amarelo e Preto');
INSERT INTO tb_team(name, stadium, color) VALUES ('Juventus', 'Allianz Stadium', 'Branco e Preto');
INSERT INTO tb_team(name, stadium, color) VALUES ('Inter Milan', 'San Siro', 'Azul e Preto');
INSERT INTO tb_team(name, stadium, color) VALUES ('AC Milan', 'San Siro', 'Vermelho e Preto');
INSERT INTO tb_team(name, stadium, color) VALUES ('Paris Saint-Germain', 'Parc des Princes', 'Azul e Vermelho');
INSERT INTO tb_team(name, stadium, color) VALUES ('Atlético Madrid', 'Wanda Metropolitano', 'Vermelho e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Sevilla', 'Ramón Sánchez-Pizjuán', 'Branco e Vermelho');
INSERT INTO tb_team(name, stadium, color) VALUES ('Ajax', 'Johan Cruyff Arena', 'Vermelho e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('PSV Eindhoven', 'Philips Stadion', 'Vermelho e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Feyenoord', 'De Kuip', 'Vermelho e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Benfica', 'Estádio da Luz', 'Vermelho e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Porto', 'Estádio do Dragão', 'Azul e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Sporting CP', 'Estádio José Alvalade', 'Verde e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Anderlecht', 'Lotto Park', 'Roxo e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Celtic', 'Celtic Park', 'Verde e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Rangers', 'Ibrox Stadium', 'Azul');
INSERT INTO tb_team(name, stadium, color) VALUES ('Galatasaray', 'Türk Telekom Stadium', 'Vermelho e Amarelo');
INSERT INTO tb_team(name, stadium, color) VALUES ('Fenerbahçe', 'Şükrü Saracoğlu Stadium', 'Amarelo e Azul');
INSERT INTO tb_team(name, stadium, color) VALUES ('Beşiktaş', 'Vodafone Park', 'Preto e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Boca Juniors', 'La Bombonera', 'Azul e Amarelo');
INSERT INTO tb_team(name, stadium, color) VALUES ('River Plate', 'Monumental', 'Branco e Vermelho');
INSERT INTO tb_team(name, stadium, color) VALUES ('Independiente', 'Libertadores de América', 'Vermelho');
INSERT INTO tb_team(name, stadium, color) VALUES ('Racing Club', 'El Cilindro', 'Azul Claro e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('San Lorenzo', 'Nuevo Gasómetro', 'Azul e Vermelho');
INSERT INTO tb_team(name, stadium, color) VALUES ('Colo-Colo', 'Estadio Monumental', 'Branco e Preto');
INSERT INTO tb_team(name, stadium, color) VALUES ('Universidad de Chile', 'Estadio Nacional', 'Azul');
INSERT INTO tb_team(name, stadium, color) VALUES ('Peñarol', 'Estadio Campeón del Siglo', 'Amarelo e Preto');
INSERT INTO tb_team(name, stadium, color) VALUES ('Nacional', 'Gran Parque Central', 'Branco, Azul e Vermelho');
INSERT INTO tb_team(name, stadium, color) VALUES ('Olympiacos', 'Karaiskakis Stadium', 'Vermelho e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Panathinaikos', 'Apostolos Nikolaidis', 'Verde e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Shakhtar Donetsk', 'Donbass Arena', 'Laranja e Preto');
INSERT INTO tb_team(name, stadium, color) VALUES ('Dynamo Kyiv', 'Olimpiyskiy Stadium', 'Branco e Azul');
INSERT INTO tb_team(name, stadium, color) VALUES ('CSKA Moscow', 'VEB Arena', 'Vermelho e Azul');
INSERT INTO tb_team(name, stadium, color) VALUES ('Spartak Moscow', 'Otkritie Arena', 'Vermelho e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Zenit Saint Petersburg', 'Krestovsky Stadium', 'Azul e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Al-Hilal', 'King Fahd Stadium', 'Azul');
INSERT INTO tb_team(name, stadium, color) VALUES ('Al-Nassr', 'Al-Awwal Park', 'Amarelo e Azul');
INSERT INTO tb_team(name, stadium, color) VALUES ('Urawa Red Diamonds', 'Saitama Stadium', 'Vermelho');
INSERT INTO tb_team(name, stadium, color) VALUES ('Gamba Osaka', 'Suita City Stadium', 'Azul e Preto');
INSERT INTO tb_team(name, stadium, color) VALUES ('Jeonbuk Hyundai Motors', 'Jeonju World Cup Stadium', 'Verde');
INSERT INTO tb_team(name, stadium, color) VALUES ('Al-Ahly', 'Cairo International Stadium', 'Vermelho');
INSERT INTO tb_team(name, stadium, color) VALUES ('Napoli', 'Stadio Diego Armando Maradona', 'Azul Claro');
INSERT INTO tb_team(name, stadium, color) VALUES ('Lazio', 'Stadio Olimpico', 'Azul Claro e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Roma', 'Stadio Olimpico', 'Amarelo e Vermelho');
INSERT INTO tb_team(name, stadium, color) VALUES ('Valencia', 'Mestalla', 'Branco e Laranja');
INSERT INTO tb_team(name, stadium, color) VALUES ('Villarreal', 'Estadio de la Cerámica', 'Amarelo');
INSERT INTO tb_team(name, stadium, color) VALUES ('Everton', 'Goodison Park', 'Azul');
INSERT INTO tb_team(name, stadium, color) VALUES ('West Ham United', 'London Stadium', 'Vinho e Azul Claro');
INSERT INTO tb_team(name, stadium, color) VALUES ('Leicester City', 'King Power Stadium', 'Azul');
INSERT INTO tb_team(name, stadium, color) VALUES ('Bayer Leverkusen', 'BayArena', 'Vermelho e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('RB Leipzig', 'Red Bull Arena', 'Branco e Vermelho');
INSERT INTO tb_team(name, stadium, color) VALUES ('Monaco', 'Stade Louis II', 'Vermelho e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Lyon', 'Groupama Stadium', 'Branco, Azul e Vermelho');
INSERT INTO tb_team(name, stadium, color) VALUES ('Marseille', 'Vélodrome', 'Branco e Azul');
INSERT INTO tb_team(name, stadium, color) VALUES ('Estudiantes', 'Estadio Jorge Luis Hirschi', 'Vermelho e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Vélez Sarsfield', 'Estadio José Amalfitani', 'Branco e Azul');
INSERT INTO tb_team(name, stadium, color) VALUES ('Emelec', 'Estadio George Capwell', 'Azul');
INSERT INTO tb_team(name, stadium, color) VALUES ('Barcelona SC', 'Estadio Monumental', 'Amarelo');
INSERT INTO tb_team(name, stadium, color) VALUES ('Club América', 'Estadio Azteca', 'Amarelo e Azul');
INSERT INTO tb_team(name, stadium, color) VALUES ('Chivas Guadalajara', 'Estadio Akron', 'Vermelho e Branco');
INSERT INTO tb_team(name, stadium, color) VALUES ('Al-Ittihad', 'King Abdullah Sports City', 'Amarelo e Preto');